version: "3.8"
services:
  db:
    image: ivanlonel/postgis-with-extensions:16-3.4
    platform: linux/amd64
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5436:5432"
    volumes:
      - ./docker/db/init/init.sql:/docker-entrypoint-initdb.d/init.sql
