[package]
name = "domain"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
chrono = { workspace = true }
email_address = "0.2.9"
fake = { workspace = true }
thiserror = { workspace = true }
uuid = { version = "1.10.0", features = ["v4", "v7"] }
